// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEuo-Dudao1X3h94mSbnbyIxjw0rYGhdQ',
    appId: '1:343332567751:web:6305765d01509d26525ce2',
    messagingSenderId: '343332567751',
    projectId: 'rezepteeinkaufslistenapp',
    authDomain: 'rezepteeinkaufslistenapp.firebaseapp.com',
    storageBucket: 'rezepteeinkaufslistenapp.firebasestorage.app',
    measurementId: 'G-5WQ63QVKXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhVmavJcn3TzG0tUD7bjvr-jAVVjwfw2g',
    appId: '1:343332567751:android:62c78bf2fd5332d6525ce2',
    messagingSenderId: '343332567751',
    projectId: 'rezepteeinkaufslistenapp',
    storageBucket: 'rezepteeinkaufslistenapp.firebasestorage.app',
  );

}